### ISSUE TITLE
gh-pages?

### ISSUE THREAD

**Issue by sky-bones** [sky-bones/dsn1678-assignment-1#1]
@thomasjbradley

gh-pages (as a branch) seems to be missing? trying to create it leads to a big mess, and there doesn't seem to be a way to delete the master, or replace it with a gh-pages. 

(There also seems to be documentation of everything BUT gh-pages) 

Main Question - should I create a gh-pages branch? or just work off the master branch?
(using github version 211)

**Comment by thomasjbradley** [comment]
You definitely have to create the `gh-pages` branch, but in the new version of the GitHub app `master` cannot be deleted, and that's okay.

**Comment by sky-bones** [comment]
Okay! Thank you :)
